name: .NET build verification

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  BuildAndTest:
    name: "Build and Test IOM"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Copy BimApiFeaClient to BimApiClientApp
      run: |
        cp src/templates/BimApiFeaClient src/templates/BimApiClientApp -r
        rm src/templates/BimApiClientApp/BimApiFeaClient/.template.config -r

    - name: Install dependencies
      run: dotnet restore src/IdeaStatiCa.Dotnet.Templates.csproj

    - name: pack
      run: dotnet build src/IdeaStatiCa.Dotnet.Templates.csproj --configuration Release

    - name: pack
      run: dotnet pack src/IdeaStatiCa.Dotnet.Templates.csproj --configuration Release -o src/nuget --no-restore

    - uses: actions/upload-artifact@v4
      with:
        name: IdeaStatiCa.Dotnet.Templates.zip
        path: src/nuget/*.nupkg     

